### ISSUE TITLE
Upgrades Tab: All items show as upgrading from -1 to 0

### ISSUE THREAD

**Issue by stevietv** [Updownquark/OGame-ROI#10]
I've just added a bunch of upgrades, however they don't reflect in the upgrades tab correctly:

![image](https://user-images.githubusercontent.com/1117625/94893914-8ea25a00-0488-11eb-8037-28e0498160db.png)

**Comment by Updownquark** [comment]
I believe I've fixed this.  As always, reopen if you see it again
