### ISSUE TITLE
Labels are not available

### ISSUE THREAD

**Issue by stevietv** [Updownquark/OGame-ROI#11]
https://github.com/Updownquark/OGame-ROI/blob/292d5989ac8494592ca356fee87dfdf6991175f8/src/org/quark/ogame/uni/ui/OGameUniGui.java#L1004-L1006

I think assigning a label to an issue may only be available to rep owners.

**Comment by Updownquark** [comment]
Oh man, I didn't know that, thanks!

**Comment by Updownquark** [comment]
This text should be removed in the latest releases
