### ISSUE TITLE
Changing from an upgrade type to "None" in the Builds tab doesn't make the cost show up in the Upgrades tab

### ISSUE THREAD

**Issue by Updownquark** [Updownquark/OGame-ROI#2]

**Comment by stevietv** [comment]
I've followed these steps with this result:
1) adjust plasma from 17 to 17/18 (shows a cost)
2) adjust Omicron from 3618 to 3618/3700 solar sats (shows no cost)
3) adjust omicron from 34 to 34/35 on C Mine (shows no cost)
4) adjust decapod from 34 to 34/35 on C Mine (shows no cost)
5) adjust tweenis from 34 to 34/35 on C mine (shows no cost)

note that omicron and decapod previously did have crystal entered in the Upgrd column, however tweenis was never touched.

![image](https://user-images.githubusercontent.com/1117625/94301873-9be0b580-ff6b-11ea-859f-6ca33c720df5.png)

![image](https://user-images.githubusercontent.com/1117625/94301893-a13e0000-ff6b-11ea-95ac-ec53e8816617.png)
