### ISSUE TITLE
mine and facilities tab upgrade column

### ISSUE THREAD

**Issue by stevietv** [Updownquark/OGame-ROI#7]
The Upgrd column on the mines tab now shows the moon facilities:

![image](https://user-images.githubusercontent.com/1117625/94490123-1d437c80-01e6-11eb-972e-254df514105c.png)

same goes for facilities tab

**Comment by Updownquark** [comment]
Woops.  :-P

**Comment by Updownquark** [comment]
Ok, think I fixed this one.  New release with just this fix.
