### ISSUE TITLE
Builds cell render bug

### ISSUE THREAD

**Issue by Updownquark** [Updownquark/OGame-ROI#8]
When an account is initially selected or a change to a goal is made in the Builds tab, the goal does not immediately show up.  If the cell is then selected or the tab is changed or anything like that, the goal shows up.

**Comment by Updownquark** [comment]
The issue is the change I made to stop re-evaluating the goal production multiple times for every event that happens.  This happens after all changes have been done.  But the render happens before this.

**Comment by stevietv** [comment]
just came by to report the same thing 👍🏻

**Comment by Updownquark** [comment]
I think this is fixed in the latest release (0.9.10), reopen if not

**Comment by Updownquark** [comment]
Although fixed in the planets table, the issue still shows up in the research table

**Comment by Updownquark** [comment]
Fixed in v0.9.12
