### ISSUE TITLE
Resource Settings: current and goals are equal

### ISSUE THREAD

**Issue by stevietv** [Updownquark/OGame-ROI#9]
although the upgrade level is shown on the goals side, the extra production is not calculated:

![image](https://user-images.githubusercontent.com/1117625/94893737-2d7a8680-0488-11eb-95ab-5747a5fac62e.png)

**Comment by stevietv** [comment]
same goes for checking the 'For Goals' box on Production tab, no change in production is reflected.

**Comment by Updownquark** [comment]
I believe I've fixed this.  As always, reopen if you see it again
